[2025-09-13T05:00:39.207+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T05:00:39.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sync_batch.copiar_mysql_a_pg manual__2025-09-13T05:00:37.618421+00:00 [queued]>
[2025-09-13T05:00:39.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sync_batch.copiar_mysql_a_pg manual__2025-09-13T05:00:37.618421+00:00 [queued]>
[2025-09-13T05:00:39.227+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-13T05:00:39.231+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copiar_mysql_a_pg> on 2025-09-13 05:00:37.618421+00:00
[2025-09-13T05:00:39.235+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_sync_batch', 'copiar_mysql_a_pg', 'manual__2025-09-13T05:00:37.618421+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_sync_batch.py', '--cfg-path', '/tmp/tmpow7_xin3']
[2025-09-13T05:00:39.236+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=245) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-13T05:00:39.236+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask copiar_mysql_a_pg
[2025-09-13T05:00:39.236+0000] {standard_task_runner.py:63} INFO - Started process 246 to run task
[2025-09-13T05:00:39.255+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_sync_batch.copiar_mysql_a_pg manual__2025-09-13T05:00:37.618421+00:00 [running]> on host 4044a091ce26
[2025-09-13T05:00:39.299+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_sync_batch' AIRFLOW_CTX_TASK_ID='copiar_mysql_a_pg' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T05:00:37.618421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T05:00:37.618421+00:00'
[2025-09-13T05:00:39.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T05:00:39.306+0000] {logging_mixin.py:188} INFO - Delta MySQL(resultado_vulnerabilidad) -> Postgres(vuln_households) aplicado.
[2025-09-13T05:00:39.306+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-13T05:00:39.306+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T05:00:39.311+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_sync_batch, task_id=copiar_mysql_a_pg, run_id=manual__2025-09-13T05:00:37.618421+00:00, execution_date=20250913T050037, start_date=20250913T050039, end_date=20250913T050039
[2025-09-13T05:00:39.337+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-13T05:00:39.346+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-13T05:00:39.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
