[2025-09-13T05:23:28.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T05:23:28.400+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sync_batch.asegurar_tablas manual__2025-09-13T05:23:27.896382+00:00 [queued]>
[2025-09-13T05:23:28.411+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sync_batch.asegurar_tablas manual__2025-09-13T05:23:27.896382+00:00 [queued]>
[2025-09-13T05:23:28.411+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-13T05:23:28.425+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): asegurar_tablas> on 2025-09-13 05:23:27.896382+00:00
[2025-09-13T05:23:28.445+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=346) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-13T05:23:28.439+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_sync_batch', 'asegurar_tablas', 'manual__2025-09-13T05:23:27.896382+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_sync_batch.py', '--cfg-path', '/tmp/tmpt_e2f9zo']
[2025-09-13T05:23:28.449+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask asegurar_tablas
[2025-09-13T05:23:28.448+0000] {standard_task_runner.py:63} INFO - Started process 347 to run task
[2025-09-13T05:23:28.517+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_sync_batch.asegurar_tablas manual__2025-09-13T05:23:27.896382+00:00 [running]> on host e809d7e3f0e7
[2025-09-13T05:23:28.633+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_sync_batch' AIRFLOW_CTX_TASK_ID='asegurar_tablas' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T05:23:27.896382+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T05:23:27.896382+00:00'
[2025-09-13T05:23:28.634+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T05:23:28.654+0000] {logging_mixin.py:188} INFO - vuln_households / etl_watermarks OK en Postgres.
[2025-09-13T05:23:28.654+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-13T05:23:28.655+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T05:23:28.664+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_sync_batch, task_id=asegurar_tablas, run_id=manual__2025-09-13T05:23:27.896382+00:00, execution_date=20250913T052327, start_date=20250913T052328, end_date=20250913T052328
[2025-09-13T05:23:28.720+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-13T05:23:28.755+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-13T05:23:28.756+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
